### ISSUE TITLE
feat: dynamic social card images / OG tags (bounty: 100 OP 🔴)

### ISSUE THREAD

**Issue by mds1** [mds1/evm-diff#2]
*This issue is eligible for a 100 OP bounty. Read [CONTRIBUTING.md](https://github.com/mds1/evm-diff/blob/main/CONTRIBUTING.md) to learn how to qualify.*

When sharing a link to compare two chains, the social card that's rendered should be dynamic, and show a summary of the comparison. Something like "X total differences between Mainnet and Optimism" as the header, with something like "Precompiles: Y differences" for each section.

This should be doable with https://vercel.com/blog/introducing-vercel-og-image-generation-fast-dynamic-social-card-images

**Comment by leovct** [comment]
Hey @mds1, I'd like to start working on this issue :)

**Comment by mds1** [comment]
@leovct just assigned, thanks!

**Comment by mds1** [comment]
Closed by https://github.com/mds1/evm-diff/pull/25
