### ISSUE TITLE
Difficulty/Prev-randao content bug

### ISSUE THREAD

**Issue by protolambda** [mds1/evm-diff#21]
The `difficulty` opcode in L1 Ethereum post-Merge returns beacon-chain RANDAO randomness, not just the difficulty. See https://eips.ethereum.org/EIPS/eip-4399

And in the Optimism diff it currently states that it "Returns a random value. As this value is set by the sequencer, it is not as reliably random as the L1 equivalent. You can use an oracle for randomness" but that is **wrong**: it actually copies over the randomness value from L1, and repeats it until the latest incorporated L1 block changes. See specs here: https://github.com/ethereum-optimism/optimism/blob/develop/specs/derivation.md#building-individual-payload-attributes

**Comment by mds1** [comment]
> but that is wrong

Ah, thanks! For reference that was pulled from this page of the docs, so seems that needs to be updated: https://community.optimism.io/docs/developers/build/differences/#opcode-differences

> it actually copies over the randomness value from L1, and repeats it until the latest incorporated L1 block changes. See specs here:

Got it. What's the spec around the lag in matching the L1 difficulty? It sounds like the L2 prevrandao value should match L1's, e.g. with the following behavior:

| Wall Clock time                   | 12:00:00 | 12:00:04 | 12:00:08 | 12:00:12 | 12:00:16 | 12:01:20 |
| --------------------------------- | -------- | ----------- | ----------- | ----------- | -------- | ----------- |
| L1 `block.number`                 | 1     | 1        | 1        | 2        | 2     | 2       |
| L2 `block.number`                 | 24     | 26        | 28        | 30        | 32     | 34        |
| L1 `block.prevrandao`                 | 2894     | 2894        | 2894        | 8506        | 8506     | 8506        |
| L2 `block.prevrandao`                 | 2894     | 2894        | 2894        | 8506        | 8506     | 8506        |

i.e. In the time L1 generates 1 block, Optimism generates 6, all with the same difficulty of the prior L1 block.

However, this isn't quite right and it seems there's some lag here. I ran the below command:

```sh
for i in {1..100}; do
  cast call 0xca11bde05977b3631167028862be2a173976ca11 "aggregate((address,bytes)[])(uint256, bytes[])" "[(0xca11bde05977b3631167028862be2a173976ca11,0x72425d9d)]" --rpc-url $MAINNET_RPC_URL
  cast call 0xca11bde05977b3631167028862be2a173976ca11 "aggregate((address,bytes)[])(uint256, bytes[])" "[(0xca11bde05977b3631167028862be2a173976ca11,0x72425d9d)]" --rpc-url $OPTIMISM_RPC_URL
  echo ""
done
```

and saw the output shown here: https://app.warp.dev/block/eBE2mbh8FQ2krhdB3bdgh9

Each group of 4 lines is `(L1 block number, L1 difficulty, Optimism block number, Optimism difficulty)`. It seems there's ~5-6 mainnet blocks worth of lag until Optimism matches the same difficulty.

**Comment by protolambda** [comment]
There is flexibility in L1-information inclusion in L2, since there may be gap-slots in the L1, or the L1 blocks may show up late / after a reorg. See "sequencer time drift" for hard properties there in the spec. All the L1 information is always included at the same time however: when the L1 block info visible in the L2 EVM (through the L1BlockInfo predeploy) changes, the PREV-RANDAO value also changes along with it at the same time.

And yes, the flexibility is used by the sequencer to generally keep a confirmation-distance of ~5 L1 blocks, to avoid having to reorg the L2 chain when the L1 chain has a shot reorg.

**Comment by mds1** [comment]
Awesome, this all makes sense. Thanks a lot!
