### ISSUE TITLE
feat: finish populating existing precompiles and predeploys (bounty: 75 OP 🔴)

### ISSUE THREAD

**Issue by mds1** [mds1/evm-diff#3]
*This issue is eligible for a 75 OP bounty. Read [CONTRIBUTING.md](https://github.com/mds1/evm-diff/blob/main/CONTRIBUTING.md) to learn how to qualify.*

This is basically a version of https://www.evm.codes/precompiled for each chain, with the addition of predeploys. This has been started but is not left complete. The remaining tasks are:

1. Search for `TODO` in any `precompiles.ts` files to reveal the uncompleted sections, and complete them.
2. All existing `references` fields should be checked for accuracy
3. Additional references should be added for more information when possible.

**Comment by cairoeth** [comment]
@mds1 Happy to take this issue. Most TODOs are related to arbitrum's precompiles, which I can complete using their docs here https://developer.arbitrum.io/arbos/precompiles. Will also check for the other references for accuracy and additional info when needed.
