### ISSUE TITLE
feat(data): JSON-RPC methods

### ISSUE THREAD

**Issue by mds1** [mds1/evm-diff#32]
*This issue is eligible for a bounty paid out in ETH on OP Mainnet. Read [CONTRIBUTING.md](https://github.com/mds1/evm-diff/blob/main/CONTRIBUTING.md) to learn how to qualify.*

- List of all standard execution-related methods and their interfaces, along with chain-specific methods. For mainnet we can start with https://ethereum.org/en/developers/docs/apis/json-rpc/. 
- Consensus layer RPCs can be ignored for now since the site focus is execution level

This is dependent on #33 as some nodes have non-standard RPC methods that others nodes (even for the same chain) don't implement, so #33 should be completed first that

**Comment by leovct** [comment]
I can work on this once #50 is merged :)

**Comment by mds1** [comment]
Closing this issue as part of the move to automated data collection in https://github.com/mds1/evm-diff/pull/62
