### ISSUE TITLE
feat(data): Nodes

### ISSUE THREAD

**Issue by mds1** [mds1/evm-diff#33]
*This issue is eligible for a bounty paid out in OP tokens. Read [CONTRIBUTING.md](https://github.com/mds1/evm-diff/blob/main/CONTRIBUTING.md) to learn how to qualify.*

- A list of all node implementations with links to their github repos and docs. I think it's ok to include both execution and consensus clients, but the latter doesn't feel necessary since data is currently execution focused 
- Differences in trace formats between nodes with e.g. `debug_traceTransaction`, `structLog`, `callTracer`, etc. (@charles-cooper I believe you suggested this originally, any references, etc. you can share? I'm not too familiar with the differences / uses for each )

**Comment by leovct** [comment]
@mul1sh Are you still working on this?
cc @mds1

**Comment by leovct** [comment]
> > @mul1sh Are you still working on this? cc @mds1
> 
> Yes I am, just got a bit overwhelmed by other stuff on my end 🥲
> 
> I'll resume working on it this coming Friday and be done by Monday.

No worries :) I can take over if needed

**Comment by mul1sh** [comment]
@leovct No worries, please take over the issue. Tbh I still have to learn the code well, so maybe I'll pick up other issues once  I've understood the code well 😃
