### ISSUE TITLE
feat(data): Block Production

### ISSUE THREAD

**Issue by mds1** [mds1/evm-diff#35]
*This issue is eligible for a bounty paid out in ETH on OP Mainnet. Read [CONTRIBUTING.md](https://github.com/mds1/evm-diff/blob/main/CONTRIBUTING.md) to learn how to qualify.*

We are only focused on things that affect execution:
- Block time
- Gas limit and pricing (1559) rules (this might be some duplicate data from #31 so consider how to reuse the data). For non-1559 chains this is a single gas limit value, for 1559 chains it's a gas target and a gas limit
- Consensus mechanism, since this enables e.g. multi-block MEV
- Finality definitions / reorg risks
- Censorship / trust assumptions on e.g. sequencers. Maybe can outsource / link to [L2Beat](https://l2beat.com) here since I think they have a lot of data around this
- Timestamp manipulation

**Comment by ayushm2003** [comment]
I would like to take this up

**Comment by mds1** [comment]
Thanks! Just tweaked the description. Feel free to DM me on telegram at msolomon4 to agree on a bounty amount and any other questions you have. My suggested plan would be:
- Open a draft PR that adds the new types along with the data for mainnet and at least one of the other chains. We'll make sure we agree on the data and data types
- Then, add the UX portion to the PR to actually render the data in a new section

**Comment by mds1** [comment]
Closing this issue as part of the move to automated data collection in https://github.com/mds1/evm-diff/pull/62. With the new architecture the data here will likely be sliced differently in some TBD way, so will create a new issue for that in the future
