### ISSUE TITLE
feat: Add Humanode network

### ISSUE THREAD

**Issue by MOZGIII** [mds1/evm-diff#42]
Would be great to add the Humanode network here.

We are planning to contribute a PR in a bit.

A mirroring issue on our side: https://github.com/humanode-network/humanode/issues/738

Humanode is a network based on direct Sybil-resistance via biometrics at the consensus level (and we have recently shipped our EVM support).

**Comment by mds1** [comment]
Hey, thanks for your interest! I'd like to hold off on adding other chains for now until we have the complete set of data for the initial chains. This set of data is all issues where the title starts with `feat(data)`. 

Once that's done, I want to add a helper method that makes it easy to add a new chain based off an existing chain, so the diffs for new chains can be small.

From there, one idea is to let chains permissionlessly add their own diffs by embedding the URL to a spec file as defined in https://github.com/mds1/evm-diff/issues/43. 

If you'd like to help tackle some of the existing data issues to more quickly reach completion for existing chains, feel free to leave a comment on issues you plan to tackle and I can assign you :)

**Comment by mds1** [comment]
Closing this issue as part of the move to automated data collection in https://github.com/mds1/evm-diff/pull/62, it will be easy to PR in support for any chain once that is ready :)
