### ISSUE TITLE
feat: diff eip1559 parameters

### ISSUE THREAD

**Issue by yzhou61** [mds1/evm-diff#8]
It will be useful to diff the parameters controlling base gas fee.

Example: https://community.optimism.io/docs/developers/bedrock/differences/#eip-1559

**Comment by mds1** [comment]
Agreed! I have this tracked in https://github.com/mds1/evm-diff/issues/4, under the "Gas" section:

> Comparison of EIP-1559 parameters, since they can be adjusted

Going to close this as a result :)
